/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OrganisationsRouteImport } from './routes/organisations'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AdminLiveRouteImport } from './routes/admin.live'
import { Route as InvitationsInvitationIdRouteImport } from './routes/invitations.$invitationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisationsRoute = OrganisationsRouteImport.update({
  id: '/organisations',
  path: '/organisations',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLiveRoute = AdminLiveRouteImport.update({
  id: '/admin/live',
  path: '/admin/live',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsInvitationIdRoute = InvitationsInvitationIdRouteImport.update({
  id: '/invitations/$invitationId',
  path: '/invitations/$invitationId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/consent': typeof ConsentRoute
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/organisations': typeof OrganisationsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/live': typeof AdminLiveRoute
  '/invitations/$invitationId': typeof InvitationsInvitationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/consent': typeof ConsentRoute
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/organisations': typeof OrganisationsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/live': typeof AdminLiveRoute
  '/invitations/$invitationId': typeof InvitationsInvitationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/consent': typeof ConsentRoute
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/organisations': typeof OrganisationsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/live': typeof AdminLiveRoute
  '/invitations/$invitationId': typeof InvitationsInvitationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/consent'
    | '/device'
    | '/login'
    | '/organisations'
    | '/register'
    | '/reset-password'
    | '/admin/live'
    | '/invitations/$invitationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/consent'
    | '/device'
    | '/login'
    | '/organisations'
    | '/register'
    | '/reset-password'
    | '/admin/live'
    | '/invitations/$invitationId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/consent'
    | '/device'
    | '/login'
    | '/organisations'
    | '/register'
    | '/reset-password'
    | '/admin/live'
    | '/invitations/$invitationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ConsentRoute: typeof ConsentRoute
  DeviceRoute: typeof DeviceRoute
  LoginRoute: typeof LoginRoute
  OrganisationsRoute: typeof OrganisationsRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AdminLiveRoute: typeof AdminLiveRoute
  InvitationsInvitationIdRoute: typeof InvitationsInvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisations': {
      id: '/organisations'
      path: '/organisations'
      fullPath: '/organisations'
      preLoaderRoute: typeof OrganisationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/live': {
      id: '/admin/live'
      path: '/admin/live'
      fullPath: '/admin/live'
      preLoaderRoute: typeof AdminLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/$invitationId': {
      id: '/invitations/$invitationId'
      path: '/invitations/$invitationId'
      fullPath: '/invitations/$invitationId'
      preLoaderRoute: typeof InvitationsInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ConsentRoute: ConsentRoute,
  DeviceRoute: DeviceRoute,
  LoginRoute: LoginRoute,
  OrganisationsRoute: OrganisationsRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AdminLiveRoute: AdminLiveRoute,
  InvitationsInvitationIdRoute: InvitationsInvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
