/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OrganisationsRouteImport } from './routes/organisations'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AccountMcpSessionsRouteImport } from './routes/account_.mcp-sessions'
import { Route as AdminLiveRouteImport } from './routes/admin.live'
import { Route as InvitationsInvitationIdRouteImport } from './routes/invitations.$invitationId'
import { Route as StoresNewRouteImport } from './routes/stores.new'
import { Route as AdminStoresStoreIdRouteImport } from './routes/admin.stores.$storeId'
import { Route as AdminStoresStoreIdFloorRouteImport } from './routes/admin.stores.$storeId.floor'
import { Route as AdminStoresStoreIdMembersRouteImport } from './routes/admin.stores.$storeId.members'
import { Route as AdminStoresStoreIdProfileRouteImport } from './routes/admin.stores.$storeId.profile'
import { Route as AdminStoresStoreIdDevicesIndexRouteImport } from './routes/admin.stores.$storeId.devices.index'
import { Route as AdminStoresStoreIdDevicesNewRouteImport } from './routes/admin.stores.$storeId.devices.new'
import { Route as AdminStoresStoreIdInvitationsIndexRouteImport } from './routes/admin.stores.$storeId.invitations.index'
import { Route as AdminStoresStoreIdInvitationsNewRouteImport } from './routes/admin.stores.$storeId.invitations.new'
import { Route as AdminStoresStoreIdMenuSectionRouteImport } from './routes/admin.stores.$storeId.menu.$section'
import { Route as AdminStoresStoreIdVisitsIndexRouteImport } from './routes/admin.stores.$storeId.visits.index'
import { Route as AdminStoresStoreIdVisitsSessionIdRouteImport } from './routes/admin.stores.$storeId.visits.$sessionId'
import { Route as AdminStoresStoreIdMenuSectionItemIdRouteImport } from './routes/admin.stores.$storeId.menu.$section_.$itemId'
import { Route as AdminStoresStoreIdMenuChangesIndexRouteImport } from './routes/admin.stores.$storeId.menu.changes.index'
import { Route as AdminStoresStoreIdMenuChangesDraftIdRouteImport } from './routes/admin.stores.$storeId.menu.changes.$draftId'
import { Route as AdminStoresStoreIdTablesTableIdOpenRouteImport } from './routes/admin.stores.$storeId.tables.$tableId.open'
import { Route as AdminStoresStoreIdMenuChangesDraftIdSectionRouteImport } from './routes/admin.stores.$storeId.menu.changes.$draftId_.$section'
import { Route as AdminStoresStoreIdMenuChangesDraftIdSectionItemIdRouteImport } from './routes/admin.stores.$storeId.menu.changes.$draftId_.$section_.$itemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisationsRoute = OrganisationsRouteImport.update({
  id: '/organisations',
  path: '/organisations',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountMcpSessionsRoute = AccountMcpSessionsRouteImport.update({
  id: '/account_/mcp-sessions',
  path: '/account/mcp-sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLiveRoute = AdminLiveRouteImport.update({
  id: '/admin/live',
  path: '/admin/live',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsInvitationIdRoute = InvitationsInvitationIdRouteImport.update({
  id: '/invitations/$invitationId',
  path: '/invitations/$invitationId',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresNewRoute = StoresNewRouteImport.update({
  id: '/stores/new',
  path: '/stores/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStoresStoreIdRoute = AdminStoresStoreIdRouteImport.update({
  id: '/admin/stores/$storeId',
  path: '/admin/stores/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStoresStoreIdFloorRoute = AdminStoresStoreIdFloorRouteImport.update({
  id: '/floor',
  path: '/floor',
  getParentRoute: () => AdminStoresStoreIdRoute,
} as any)
const AdminStoresStoreIdMembersRoute =
  AdminStoresStoreIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AdminStoresStoreIdRoute,
  } as any)
const AdminStoresStoreIdProfileRoute =
  AdminStoresStoreIdProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AdminStoresStoreIdRoute,
  } as any)
const AdminStoresStoreIdDevicesIndexRoute =
  AdminStoresStoreIdDevicesIndexRouteImport.update({
    id: '/devices/',
    path: '/devices/',
    getParentRoute: () => AdminStoresStoreIdRoute,
  } as any)
const AdminStoresStoreIdDevicesNewRoute =
  AdminStoresStoreIdDevicesNewRouteImport.update({
    id: '/devices/new',
    path: '/devices/new',
    getParentRoute: () => AdminStoresStoreIdRoute,
  } as any)
const AdminStoresStoreIdInvitationsIndexRoute =
  AdminStoresStoreIdInvitationsIndexRouteImport.update({
    id: '/invitations/',
    path: '/invitations/',
    getParentRoute: () => AdminStoresStoreIdRoute,
  } as any)
const AdminStoresStoreIdInvitationsNewRoute =
  AdminStoresStoreIdInvitationsNewRouteImport.update({
    id: '/invitations/new',
    path: '/invitations/new',
    getParentRoute: () => AdminStoresStoreIdRoute,
  } as any)
const AdminStoresStoreIdMenuSectionRoute =
  AdminStoresStoreIdMenuSectionRouteImport.update({
    id: '/menu/$section',
    path: '/menu/$section',
    getParentRoute: () => AdminStoresStoreIdRoute,
  } as any)
const AdminStoresStoreIdVisitsIndexRoute =
  AdminStoresStoreIdVisitsIndexRouteImport.update({
    id: '/visits/',
    path: '/visits/',
    getParentRoute: () => AdminStoresStoreIdRoute,
  } as any)
const AdminStoresStoreIdVisitsSessionIdRoute =
  AdminStoresStoreIdVisitsSessionIdRouteImport.update({
    id: '/visits/$sessionId',
    path: '/visits/$sessionId',
    getParentRoute: () => AdminStoresStoreIdRoute,
  } as any)
const AdminStoresStoreIdMenuSectionItemIdRoute =
  AdminStoresStoreIdMenuSectionItemIdRouteImport.update({
    id: '/menu/$section_/$itemId',
    path: '/menu/$section/$itemId',
    getParentRoute: () => AdminStoresStoreIdRoute,
  } as any)
const AdminStoresStoreIdMenuChangesIndexRoute =
  AdminStoresStoreIdMenuChangesIndexRouteImport.update({
    id: '/menu/changes/',
    path: '/menu/changes/',
    getParentRoute: () => AdminStoresStoreIdRoute,
  } as any)
const AdminStoresStoreIdMenuChangesDraftIdRoute =
  AdminStoresStoreIdMenuChangesDraftIdRouteImport.update({
    id: '/menu/changes/$draftId',
    path: '/menu/changes/$draftId',
    getParentRoute: () => AdminStoresStoreIdRoute,
  } as any)
const AdminStoresStoreIdTablesTableIdOpenRoute =
  AdminStoresStoreIdTablesTableIdOpenRouteImport.update({
    id: '/tables/$tableId/open',
    path: '/tables/$tableId/open',
    getParentRoute: () => AdminStoresStoreIdRoute,
  } as any)
const AdminStoresStoreIdMenuChangesDraftIdSectionRoute =
  AdminStoresStoreIdMenuChangesDraftIdSectionRouteImport.update({
    id: '/menu/changes/$draftId_/$section',
    path: '/menu/changes/$draftId/$section',
    getParentRoute: () => AdminStoresStoreIdRoute,
  } as any)
const AdminStoresStoreIdMenuChangesDraftIdSectionItemIdRoute =
  AdminStoresStoreIdMenuChangesDraftIdSectionItemIdRouteImport.update({
    id: '/menu/changes/$draftId_/$section_/$itemId',
    path: '/menu/changes/$draftId/$section/$itemId',
    getParentRoute: () => AdminStoresStoreIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/consent': typeof ConsentRoute
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/organisations': typeof OrganisationsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account/mcp-sessions': typeof AccountMcpSessionsRoute
  '/admin/live': typeof AdminLiveRoute
  '/invitations/$invitationId': typeof InvitationsInvitationIdRoute
  '/stores/new': typeof StoresNewRoute
  '/admin/stores/$storeId': typeof AdminStoresStoreIdRouteWithChildren
  '/admin/stores/$storeId/floor': typeof AdminStoresStoreIdFloorRoute
  '/admin/stores/$storeId/members': typeof AdminStoresStoreIdMembersRoute
  '/admin/stores/$storeId/profile': typeof AdminStoresStoreIdProfileRoute
  '/admin/stores/$storeId/devices/new': typeof AdminStoresStoreIdDevicesNewRoute
  '/admin/stores/$storeId/invitations/new': typeof AdminStoresStoreIdInvitationsNewRoute
  '/admin/stores/$storeId/menu/$section': typeof AdminStoresStoreIdMenuSectionRoute
  '/admin/stores/$storeId/visits/$sessionId': typeof AdminStoresStoreIdVisitsSessionIdRoute
  '/admin/stores/$storeId/devices/': typeof AdminStoresStoreIdDevicesIndexRoute
  '/admin/stores/$storeId/invitations/': typeof AdminStoresStoreIdInvitationsIndexRoute
  '/admin/stores/$storeId/visits/': typeof AdminStoresStoreIdVisitsIndexRoute
  '/admin/stores/$storeId/menu/$section/$itemId': typeof AdminStoresStoreIdMenuSectionItemIdRoute
  '/admin/stores/$storeId/menu/changes/$draftId': typeof AdminStoresStoreIdMenuChangesDraftIdRoute
  '/admin/stores/$storeId/tables/$tableId/open': typeof AdminStoresStoreIdTablesTableIdOpenRoute
  '/admin/stores/$storeId/menu/changes/': typeof AdminStoresStoreIdMenuChangesIndexRoute
  '/admin/stores/$storeId/menu/changes/$draftId/$section': typeof AdminStoresStoreIdMenuChangesDraftIdSectionRoute
  '/admin/stores/$storeId/menu/changes/$draftId/$section/$itemId': typeof AdminStoresStoreIdMenuChangesDraftIdSectionItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/consent': typeof ConsentRoute
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/organisations': typeof OrganisationsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account/mcp-sessions': typeof AccountMcpSessionsRoute
  '/admin/live': typeof AdminLiveRoute
  '/invitations/$invitationId': typeof InvitationsInvitationIdRoute
  '/stores/new': typeof StoresNewRoute
  '/admin/stores/$storeId': typeof AdminStoresStoreIdRouteWithChildren
  '/admin/stores/$storeId/floor': typeof AdminStoresStoreIdFloorRoute
  '/admin/stores/$storeId/members': typeof AdminStoresStoreIdMembersRoute
  '/admin/stores/$storeId/profile': typeof AdminStoresStoreIdProfileRoute
  '/admin/stores/$storeId/devices/new': typeof AdminStoresStoreIdDevicesNewRoute
  '/admin/stores/$storeId/invitations/new': typeof AdminStoresStoreIdInvitationsNewRoute
  '/admin/stores/$storeId/menu/$section': typeof AdminStoresStoreIdMenuSectionRoute
  '/admin/stores/$storeId/visits/$sessionId': typeof AdminStoresStoreIdVisitsSessionIdRoute
  '/admin/stores/$storeId/devices': typeof AdminStoresStoreIdDevicesIndexRoute
  '/admin/stores/$storeId/invitations': typeof AdminStoresStoreIdInvitationsIndexRoute
  '/admin/stores/$storeId/visits': typeof AdminStoresStoreIdVisitsIndexRoute
  '/admin/stores/$storeId/menu/$section/$itemId': typeof AdminStoresStoreIdMenuSectionItemIdRoute
  '/admin/stores/$storeId/menu/changes/$draftId': typeof AdminStoresStoreIdMenuChangesDraftIdRoute
  '/admin/stores/$storeId/tables/$tableId/open': typeof AdminStoresStoreIdTablesTableIdOpenRoute
  '/admin/stores/$storeId/menu/changes': typeof AdminStoresStoreIdMenuChangesIndexRoute
  '/admin/stores/$storeId/menu/changes/$draftId/$section': typeof AdminStoresStoreIdMenuChangesDraftIdSectionRoute
  '/admin/stores/$storeId/menu/changes/$draftId/$section/$itemId': typeof AdminStoresStoreIdMenuChangesDraftIdSectionItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/consent': typeof ConsentRoute
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/organisations': typeof OrganisationsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account_/mcp-sessions': typeof AccountMcpSessionsRoute
  '/admin/live': typeof AdminLiveRoute
  '/invitations/$invitationId': typeof InvitationsInvitationIdRoute
  '/stores/new': typeof StoresNewRoute
  '/admin/stores/$storeId': typeof AdminStoresStoreIdRouteWithChildren
  '/admin/stores/$storeId/floor': typeof AdminStoresStoreIdFloorRoute
  '/admin/stores/$storeId/members': typeof AdminStoresStoreIdMembersRoute
  '/admin/stores/$storeId/profile': typeof AdminStoresStoreIdProfileRoute
  '/admin/stores/$storeId/devices/new': typeof AdminStoresStoreIdDevicesNewRoute
  '/admin/stores/$storeId/invitations/new': typeof AdminStoresStoreIdInvitationsNewRoute
  '/admin/stores/$storeId/menu/$section': typeof AdminStoresStoreIdMenuSectionRoute
  '/admin/stores/$storeId/visits/$sessionId': typeof AdminStoresStoreIdVisitsSessionIdRoute
  '/admin/stores/$storeId/devices/': typeof AdminStoresStoreIdDevicesIndexRoute
  '/admin/stores/$storeId/invitations/': typeof AdminStoresStoreIdInvitationsIndexRoute
  '/admin/stores/$storeId/visits/': typeof AdminStoresStoreIdVisitsIndexRoute
  '/admin/stores/$storeId/menu/$section_/$itemId': typeof AdminStoresStoreIdMenuSectionItemIdRoute
  '/admin/stores/$storeId/menu/changes/$draftId': typeof AdminStoresStoreIdMenuChangesDraftIdRoute
  '/admin/stores/$storeId/tables/$tableId/open': typeof AdminStoresStoreIdTablesTableIdOpenRoute
  '/admin/stores/$storeId/menu/changes/': typeof AdminStoresStoreIdMenuChangesIndexRoute
  '/admin/stores/$storeId/menu/changes/$draftId_/$section': typeof AdminStoresStoreIdMenuChangesDraftIdSectionRoute
  '/admin/stores/$storeId/menu/changes/$draftId_/$section_/$itemId': typeof AdminStoresStoreIdMenuChangesDraftIdSectionItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/consent'
    | '/device'
    | '/login'
    | '/organisations'
    | '/register'
    | '/reset-password'
    | '/account/mcp-sessions'
    | '/admin/live'
    | '/invitations/$invitationId'
    | '/stores/new'
    | '/admin/stores/$storeId'
    | '/admin/stores/$storeId/floor'
    | '/admin/stores/$storeId/members'
    | '/admin/stores/$storeId/profile'
    | '/admin/stores/$storeId/devices/new'
    | '/admin/stores/$storeId/invitations/new'
    | '/admin/stores/$storeId/menu/$section'
    | '/admin/stores/$storeId/visits/$sessionId'
    | '/admin/stores/$storeId/devices/'
    | '/admin/stores/$storeId/invitations/'
    | '/admin/stores/$storeId/visits/'
    | '/admin/stores/$storeId/menu/$section/$itemId'
    | '/admin/stores/$storeId/menu/changes/$draftId'
    | '/admin/stores/$storeId/tables/$tableId/open'
    | '/admin/stores/$storeId/menu/changes/'
    | '/admin/stores/$storeId/menu/changes/$draftId/$section'
    | '/admin/stores/$storeId/menu/changes/$draftId/$section/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/consent'
    | '/device'
    | '/login'
    | '/organisations'
    | '/register'
    | '/reset-password'
    | '/account/mcp-sessions'
    | '/admin/live'
    | '/invitations/$invitationId'
    | '/stores/new'
    | '/admin/stores/$storeId'
    | '/admin/stores/$storeId/floor'
    | '/admin/stores/$storeId/members'
    | '/admin/stores/$storeId/profile'
    | '/admin/stores/$storeId/devices/new'
    | '/admin/stores/$storeId/invitations/new'
    | '/admin/stores/$storeId/menu/$section'
    | '/admin/stores/$storeId/visits/$sessionId'
    | '/admin/stores/$storeId/devices'
    | '/admin/stores/$storeId/invitations'
    | '/admin/stores/$storeId/visits'
    | '/admin/stores/$storeId/menu/$section/$itemId'
    | '/admin/stores/$storeId/menu/changes/$draftId'
    | '/admin/stores/$storeId/tables/$tableId/open'
    | '/admin/stores/$storeId/menu/changes'
    | '/admin/stores/$storeId/menu/changes/$draftId/$section'
    | '/admin/stores/$storeId/menu/changes/$draftId/$section/$itemId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/consent'
    | '/device'
    | '/login'
    | '/organisations'
    | '/register'
    | '/reset-password'
    | '/account_/mcp-sessions'
    | '/admin/live'
    | '/invitations/$invitationId'
    | '/stores/new'
    | '/admin/stores/$storeId'
    | '/admin/stores/$storeId/floor'
    | '/admin/stores/$storeId/members'
    | '/admin/stores/$storeId/profile'
    | '/admin/stores/$storeId/devices/new'
    | '/admin/stores/$storeId/invitations/new'
    | '/admin/stores/$storeId/menu/$section'
    | '/admin/stores/$storeId/visits/$sessionId'
    | '/admin/stores/$storeId/devices/'
    | '/admin/stores/$storeId/invitations/'
    | '/admin/stores/$storeId/visits/'
    | '/admin/stores/$storeId/menu/$section_/$itemId'
    | '/admin/stores/$storeId/menu/changes/$draftId'
    | '/admin/stores/$storeId/tables/$tableId/open'
    | '/admin/stores/$storeId/menu/changes/'
    | '/admin/stores/$storeId/menu/changes/$draftId_/$section'
    | '/admin/stores/$storeId/menu/changes/$draftId_/$section_/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ConsentRoute: typeof ConsentRoute
  DeviceRoute: typeof DeviceRoute
  LoginRoute: typeof LoginRoute
  OrganisationsRoute: typeof OrganisationsRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AccountMcpSessionsRoute: typeof AccountMcpSessionsRoute
  AdminLiveRoute: typeof AdminLiveRoute
  InvitationsInvitationIdRoute: typeof InvitationsInvitationIdRoute
  StoresNewRoute: typeof StoresNewRoute
  AdminStoresStoreIdRoute: typeof AdminStoresStoreIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisations': {
      id: '/organisations'
      path: '/organisations'
      fullPath: '/organisations'
      preLoaderRoute: typeof OrganisationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/mcp-sessions': {
      id: '/account_/mcp-sessions'
      path: '/account/mcp-sessions'
      fullPath: '/account/mcp-sessions'
      preLoaderRoute: typeof AccountMcpSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/live': {
      id: '/admin/live'
      path: '/admin/live'
      fullPath: '/admin/live'
      preLoaderRoute: typeof AdminLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/$invitationId': {
      id: '/invitations/$invitationId'
      path: '/invitations/$invitationId'
      fullPath: '/invitations/$invitationId'
      preLoaderRoute: typeof InvitationsInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/new': {
      id: '/stores/new'
      path: '/stores/new'
      fullPath: '/stores/new'
      preLoaderRoute: typeof StoresNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stores/$storeId': {
      id: '/admin/stores/$storeId'
      path: '/admin/stores/$storeId'
      fullPath: '/admin/stores/$storeId'
      preLoaderRoute: typeof AdminStoresStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stores/$storeId/floor': {
      id: '/admin/stores/$storeId/floor'
      path: '/floor'
      fullPath: '/admin/stores/$storeId/floor'
      preLoaderRoute: typeof AdminStoresStoreIdFloorRouteImport
      parentRoute: typeof AdminStoresStoreIdRoute
    }
    '/admin/stores/$storeId/members': {
      id: '/admin/stores/$storeId/members'
      path: '/members'
      fullPath: '/admin/stores/$storeId/members'
      preLoaderRoute: typeof AdminStoresStoreIdMembersRouteImport
      parentRoute: typeof AdminStoresStoreIdRoute
    }
    '/admin/stores/$storeId/profile': {
      id: '/admin/stores/$storeId/profile'
      path: '/profile'
      fullPath: '/admin/stores/$storeId/profile'
      preLoaderRoute: typeof AdminStoresStoreIdProfileRouteImport
      parentRoute: typeof AdminStoresStoreIdRoute
    }
    '/admin/stores/$storeId/devices/': {
      id: '/admin/stores/$storeId/devices/'
      path: '/devices'
      fullPath: '/admin/stores/$storeId/devices/'
      preLoaderRoute: typeof AdminStoresStoreIdDevicesIndexRouteImport
      parentRoute: typeof AdminStoresStoreIdRoute
    }
    '/admin/stores/$storeId/devices/new': {
      id: '/admin/stores/$storeId/devices/new'
      path: '/devices/new'
      fullPath: '/admin/stores/$storeId/devices/new'
      preLoaderRoute: typeof AdminStoresStoreIdDevicesNewRouteImport
      parentRoute: typeof AdminStoresStoreIdRoute
    }
    '/admin/stores/$storeId/invitations/': {
      id: '/admin/stores/$storeId/invitations/'
      path: '/invitations'
      fullPath: '/admin/stores/$storeId/invitations/'
      preLoaderRoute: typeof AdminStoresStoreIdInvitationsIndexRouteImport
      parentRoute: typeof AdminStoresStoreIdRoute
    }
    '/admin/stores/$storeId/invitations/new': {
      id: '/admin/stores/$storeId/invitations/new'
      path: '/invitations/new'
      fullPath: '/admin/stores/$storeId/invitations/new'
      preLoaderRoute: typeof AdminStoresStoreIdInvitationsNewRouteImport
      parentRoute: typeof AdminStoresStoreIdRoute
    }
    '/admin/stores/$storeId/menu/$section': {
      id: '/admin/stores/$storeId/menu/$section'
      path: '/menu/$section'
      fullPath: '/admin/stores/$storeId/menu/$section'
      preLoaderRoute: typeof AdminStoresStoreIdMenuSectionRouteImport
      parentRoute: typeof AdminStoresStoreIdRoute
    }
    '/admin/stores/$storeId/visits/': {
      id: '/admin/stores/$storeId/visits/'
      path: '/visits'
      fullPath: '/admin/stores/$storeId/visits/'
      preLoaderRoute: typeof AdminStoresStoreIdVisitsIndexRouteImport
      parentRoute: typeof AdminStoresStoreIdRoute
    }
    '/admin/stores/$storeId/visits/$sessionId': {
      id: '/admin/stores/$storeId/visits/$sessionId'
      path: '/visits/$sessionId'
      fullPath: '/admin/stores/$storeId/visits/$sessionId'
      preLoaderRoute: typeof AdminStoresStoreIdVisitsSessionIdRouteImport
      parentRoute: typeof AdminStoresStoreIdRoute
    }
    '/admin/stores/$storeId/menu/$section_/$itemId': {
      id: '/admin/stores/$storeId/menu/$section_/$itemId'
      path: '/menu/$section/$itemId'
      fullPath: '/admin/stores/$storeId/menu/$section/$itemId'
      preLoaderRoute: typeof AdminStoresStoreIdMenuSectionItemIdRouteImport
      parentRoute: typeof AdminStoresStoreIdRoute
    }
    '/admin/stores/$storeId/menu/changes/': {
      id: '/admin/stores/$storeId/menu/changes/'
      path: '/menu/changes'
      fullPath: '/admin/stores/$storeId/menu/changes/'
      preLoaderRoute: typeof AdminStoresStoreIdMenuChangesIndexRouteImport
      parentRoute: typeof AdminStoresStoreIdRoute
    }
    '/admin/stores/$storeId/menu/changes/$draftId': {
      id: '/admin/stores/$storeId/menu/changes/$draftId'
      path: '/menu/changes/$draftId'
      fullPath: '/admin/stores/$storeId/menu/changes/$draftId'
      preLoaderRoute: typeof AdminStoresStoreIdMenuChangesDraftIdRouteImport
      parentRoute: typeof AdminStoresStoreIdRoute
    }
    '/admin/stores/$storeId/tables/$tableId/open': {
      id: '/admin/stores/$storeId/tables/$tableId/open'
      path: '/tables/$tableId/open'
      fullPath: '/admin/stores/$storeId/tables/$tableId/open'
      preLoaderRoute: typeof AdminStoresStoreIdTablesTableIdOpenRouteImport
      parentRoute: typeof AdminStoresStoreIdRoute
    }
    '/admin/stores/$storeId/menu/changes/$draftId_/$section': {
      id: '/admin/stores/$storeId/menu/changes/$draftId_/$section'
      path: '/menu/changes/$draftId/$section'
      fullPath: '/admin/stores/$storeId/menu/changes/$draftId/$section'
      preLoaderRoute: typeof AdminStoresStoreIdMenuChangesDraftIdSectionRouteImport
      parentRoute: typeof AdminStoresStoreIdRoute
    }
    '/admin/stores/$storeId/menu/changes/$draftId_/$section_/$itemId': {
      id: '/admin/stores/$storeId/menu/changes/$draftId_/$section_/$itemId'
      path: '/menu/changes/$draftId/$section/$itemId'
      fullPath: '/admin/stores/$storeId/menu/changes/$draftId/$section/$itemId'
      preLoaderRoute: typeof AdminStoresStoreIdMenuChangesDraftIdSectionItemIdRouteImport
      parentRoute: typeof AdminStoresStoreIdRoute
    }
  }
}

interface AdminStoresStoreIdRouteChildren {
  AdminStoresStoreIdFloorRoute: typeof AdminStoresStoreIdFloorRoute
  AdminStoresStoreIdMembersRoute: typeof AdminStoresStoreIdMembersRoute
  AdminStoresStoreIdProfileRoute: typeof AdminStoresStoreIdProfileRoute
  AdminStoresStoreIdDevicesNewRoute: typeof AdminStoresStoreIdDevicesNewRoute
  AdminStoresStoreIdInvitationsNewRoute: typeof AdminStoresStoreIdInvitationsNewRoute
  AdminStoresStoreIdMenuSectionRoute: typeof AdminStoresStoreIdMenuSectionRoute
  AdminStoresStoreIdVisitsSessionIdRoute: typeof AdminStoresStoreIdVisitsSessionIdRoute
  AdminStoresStoreIdDevicesIndexRoute: typeof AdminStoresStoreIdDevicesIndexRoute
  AdminStoresStoreIdInvitationsIndexRoute: typeof AdminStoresStoreIdInvitationsIndexRoute
  AdminStoresStoreIdVisitsIndexRoute: typeof AdminStoresStoreIdVisitsIndexRoute
  AdminStoresStoreIdMenuSectionItemIdRoute: typeof AdminStoresStoreIdMenuSectionItemIdRoute
  AdminStoresStoreIdMenuChangesDraftIdRoute: typeof AdminStoresStoreIdMenuChangesDraftIdRoute
  AdminStoresStoreIdTablesTableIdOpenRoute: typeof AdminStoresStoreIdTablesTableIdOpenRoute
  AdminStoresStoreIdMenuChangesIndexRoute: typeof AdminStoresStoreIdMenuChangesIndexRoute
  AdminStoresStoreIdMenuChangesDraftIdSectionRoute: typeof AdminStoresStoreIdMenuChangesDraftIdSectionRoute
  AdminStoresStoreIdMenuChangesDraftIdSectionItemIdRoute: typeof AdminStoresStoreIdMenuChangesDraftIdSectionItemIdRoute
}

const AdminStoresStoreIdRouteChildren: AdminStoresStoreIdRouteChildren = {
  AdminStoresStoreIdFloorRoute: AdminStoresStoreIdFloorRoute,
  AdminStoresStoreIdMembersRoute: AdminStoresStoreIdMembersRoute,
  AdminStoresStoreIdProfileRoute: AdminStoresStoreIdProfileRoute,
  AdminStoresStoreIdDevicesNewRoute: AdminStoresStoreIdDevicesNewRoute,
  AdminStoresStoreIdInvitationsNewRoute: AdminStoresStoreIdInvitationsNewRoute,
  AdminStoresStoreIdMenuSectionRoute: AdminStoresStoreIdMenuSectionRoute,
  AdminStoresStoreIdVisitsSessionIdRoute:
    AdminStoresStoreIdVisitsSessionIdRoute,
  AdminStoresStoreIdDevicesIndexRoute: AdminStoresStoreIdDevicesIndexRoute,
  AdminStoresStoreIdInvitationsIndexRoute:
    AdminStoresStoreIdInvitationsIndexRoute,
  AdminStoresStoreIdVisitsIndexRoute: AdminStoresStoreIdVisitsIndexRoute,
  AdminStoresStoreIdMenuSectionItemIdRoute:
    AdminStoresStoreIdMenuSectionItemIdRoute,
  AdminStoresStoreIdMenuChangesDraftIdRoute:
    AdminStoresStoreIdMenuChangesDraftIdRoute,
  AdminStoresStoreIdTablesTableIdOpenRoute:
    AdminStoresStoreIdTablesTableIdOpenRoute,
  AdminStoresStoreIdMenuChangesIndexRoute:
    AdminStoresStoreIdMenuChangesIndexRoute,
  AdminStoresStoreIdMenuChangesDraftIdSectionRoute:
    AdminStoresStoreIdMenuChangesDraftIdSectionRoute,
  AdminStoresStoreIdMenuChangesDraftIdSectionItemIdRoute:
    AdminStoresStoreIdMenuChangesDraftIdSectionItemIdRoute,
}

const AdminStoresStoreIdRouteWithChildren =
  AdminStoresStoreIdRoute._addFileChildren(AdminStoresStoreIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ConsentRoute: ConsentRoute,
  DeviceRoute: DeviceRoute,
  LoginRoute: LoginRoute,
  OrganisationsRoute: OrganisationsRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AccountMcpSessionsRoute: AccountMcpSessionsRoute,
  AdminLiveRoute: AdminLiveRoute,
  InvitationsInvitationIdRoute: InvitationsInvitationIdRoute,
  StoresNewRoute: StoresNewRoute,
  AdminStoresStoreIdRoute: AdminStoresStoreIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
