/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false --strict-vars=false --env-interface=TablecastEnv src/cloudflare-env.d.ts` (hash: 54f160062478e2b3297f3907c3e4dea8)
interface __BaseEnv_TablecastEnv {
	TABLECAST_MEDIA: R2Bucket;
	TABLECAST_DB: D1Database;
	TABLECAST_IMAGES: ImagesBinding;
	TABLECAST_PUBLIC_ORIGIN: string;
	TABLECAST_ENV: string;
	TABLECAST_RELEASE_SHA: string;
	TABLECAST_AUTH_SECRET: string;
	TABLECAST_VOICE_API_TOKEN: string;
	TABLECAST_VOICE_ENABLED: string;
	TABLECAST_GOOGLE_CLIENT_ID: string;
	TABLECAST_GOOGLE_CLIENT_SECRET: string;
	TABLECAST_LIVEKIT_URL: string;
	TABLECAST_LIVEKIT_API_KEY: string;
	TABLECAST_LIVEKIT_API_SECRET: string;
	TABLECAST_MODEL_API_KEY: string;
	TABLECAST_MODEL: string;
	TABLECAST_EVENTS: DurableObjectNamespace<import("./worker").StoreEvents>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "StoreEvents";
	}
	interface Env extends __BaseEnv_TablecastEnv {}
}
interface TablecastEnv extends __BaseEnv_TablecastEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TABLECAST_PUBLIC_ORIGIN" | "TABLECAST_ENV" | "TABLECAST_RELEASE_SHA" | "TABLECAST_AUTH_SECRET" | "TABLECAST_VOICE_API_TOKEN" | "TABLECAST_VOICE_ENABLED" | "TABLECAST_GOOGLE_CLIENT_ID" | "TABLECAST_GOOGLE_CLIENT_SECRET" | "TABLECAST_LIVEKIT_URL" | "TABLECAST_LIVEKIT_API_KEY" | "TABLECAST_LIVEKIT_API_SECRET" | "TABLECAST_MODEL_API_KEY" | "TABLECAST_MODEL">> {}
}
