/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false --strict-vars=false --env-interface=TablecastEnv src/cloudflare-env.d.ts` (hash: f98d78acef2d2f4efa646bc3884a8803)
interface __BaseEnv_TablecastEnv {
	TABLECAST_MEDIA: R2Bucket;
	TABLECAST_DB: D1Database;
	TABLECAST_EMAIL: SendEmail;
	TABLECAST_IMAGES: ImagesBinding;
	TABLECAST_PUBLIC_ORIGIN: string;
	TABLECAST_ENV: string;
	TABLECAST_RELEASE_SHA: string;
	TABLECAST_AUTH_SECRET: string;
	TABLECAST_BETTER_AUTH_API_KEY: string;
	TABLECAST_VOICE_API_TOKEN: string;
	TABLECAST_VOICE_ENABLED: string;
	TABLECAST_GOOGLE_CLIENT_ID: string;
	TABLECAST_GOOGLE_CLIENT_SECRET: string;
	TABLECAST_LIVEKIT_URL: string;
	TABLECAST_LIVEKIT_API_KEY: string;
	TABLECAST_LIVEKIT_API_SECRET: string;
	TABLECAST_MODEL_API_KEY: string;
	TABLECAST_MODEL: string;
	TABLECAST_GOOGLE_EMULATOR_URL: string;
	TABLECAST_EMAIL_FROM: string;
	TABLECAST_MAILPIT_URL: string;
	TABLECAST_GOOGLE_AUTHORIZE_URL: string;
	TABLECAST_CONTAINERS_ENABLED: string;
	TABLECAST_AGENT_NAME: string;
	OPENAI_API_KEY: string;
	CF_ACCESS_CLIENT_ID: string;
	CF_ACCESS_CLIENT_SECRET: string;
	TABLECAST_OTEL_CAPTURE_CONTENT: string;
	TABLECAST_PR_NUMBER: string;
	TABLECAST_OTEL_ENDPOINT: string;
	TABLECAST_OTEL_AUTHORIZATION: string;
	TABLECAST_MASTRA_ACCESS_TOKEN: string;
	TABLECAST_MASTRA_PROJECT_ID: string;
	TABLECAST_MASTRA_ENDPOINT: string;
	TABLECAST_CLOUDFLARE_ACCOUNT_ID: string;
	TABLECAST_CONTAINER_METRICS_TOKEN: string;
	TABLECAST_CONTAINER_METRICS_APPLICATIONS: string;
	TABLECAST_EVENTS: DurableObjectNamespace<import("./worker").StoreEvents>;
	TABLECAST_VOICE: DurableObjectNamespace<import("./worker").TablecastVoice>;
	TABLECAST_EMULATE: DurableObjectNamespace<import("./worker").TablecastEmulate>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "StoreEvents" | "TablecastVoice" | "TablecastEmulate";
	}
	interface Env extends __BaseEnv_TablecastEnv {}
}
interface TablecastEnv extends __BaseEnv_TablecastEnv {}
