import { demoImageKey } from "./tablecast-seed-media";

// 写真で比べる選択肢だけを紐付ける。温度・辛さ・なし等は画像を持たない。
const optionImageFiles: Readonly<Partial<Record<string, string>>> = {
  "tablecast-komorebi-serving-taster": "komorebi-option-serving-taster.webp",
  "tablecast-komorebi-serving-glass": "komorebi-option-serving-glass.webp",
  "tablecast-komorebi-serving-tokkuri": "komorebi-option-serving-tokkuri.webp",
  "tablecast-komorebi-serving-carafe": "komorebi-option-serving-carafe.webp",
  "tablecast-komorebi-garnish-ginger": "komorebi-option-garnish-ginger.webp",
  "tablecast-komorebi-garnish-wasabi": "komorebi-option-garnish-wasabi.webp",
  "tablecast-komorebi-garnish-shiso": "komorebi-option-garnish-shiso.webp",
  "tablecast-komorebi-garnish-lemon": "komorebi-option-garnish-lemon.webp",
  "tablecast-komorebi-seasoning-salt": "komorebi-option-seasoning-salt.webp",
  "tablecast-komorebi-seasoning-tare": "komorebi-option-seasoning-tare.webp",
  "tablecast-komorebi-seasoning-ponzu": "komorebi-option-seasoning-ponzu.webp",
  "tablecast-komorebi-topping-scallion": "komorebi-option-topping-scallion.webp",
  "tablecast-komorebi-topping-radish": "komorebi-option-topping-radish.webp",
  "tablecast-komorebi-topping-nori": "komorebi-option-topping-nori.webp",
  "tablecast-komorebi-topping-egg": "komorebi-option-topping-egg.webp",
  "tablecast-komorebi-broth-bonito": "komorebi-option-broth-bonito.webp",
  "tablecast-komorebi-broth-kombu": "komorebi-option-broth-kombu.webp",
  "tablecast-komorebi-broth-chicken": "komorebi-option-broth-chicken.webp",
  "tablecast-komorebi-broth-miso": "komorebi-option-broth-miso.webp",
  "tablecast-komorebi-ice-iced": "komorebi-option-ice-iced.webp",
  "tablecast-komorebi-ice-less": "komorebi-option-ice-less.webp",
  "tablecast-komorebi-ice-none": "komorebi-option-ice-none.webp",
  "tablecast-komorebi-ice-hot": "komorebi-option-ice-hot.webp",
  "tablecast-koharu-bun-brioche": "westward-option-bun-brioche.webp",
  "tablecast-koharu-bun-wholemeal": "westward-option-bun-wholemeal.webp",
  "tablecast-koharu-bun-lettuce": "westward-option-bun-lettuce.webp",
  "tablecast-koharu-patty-beef": "westward-option-patty-beef.webp",
  "tablecast-koharu-patty-plant": "westward-option-patty-plant.webp",
  "tablecast-koharu-cheese-cheddar": "westward-option-cheddar.webp",
  "tablecast-koharu-cheese-pepper-jack": "westward-option-cheese-pepper-jack.webp",
  "tablecast-koharu-omit-onion": "westward-option-omit-onion.webp",
  "tablecast-koharu-omit-tomato": "westward-option-omit-tomato.webp",
  "tablecast-koharu-omit-pickle": "westward-option-omit-pickle.webp",
  "tablecast-koharu-sauce-house": "westward-option-sauce-house.webp",
  "tablecast-koharu-sauce-mustard": "westward-option-sauce-mustard.webp",
  "tablecast-koharu-sauce-bbq": "westward-option-sauce-bbq.webp",
  "tablecast-koharu-extras-cheddar": "westward-option-cheddar.webp",
  "tablecast-koharu-extras-avocado": "westward-option-extras-avocado.webp",
  "tablecast-koharu-extras-bacon": "westward-option-extras-bacon.webp",
  "tablecast-koharu-beer-serving-small": "westward-option-beer-serving-small.webp",
  "tablecast-koharu-beer-serving-pint": "westward-option-beer-serving-pint.webp",
  "tablecast-hanul-rice-small": "hanul-option-rice-small.webp",
  "tablecast-hanul-rice-regular": "hanul-option-rice-regular.webp",
  "tablecast-hanul-wraps-lettuce": "hanul-option-wraps-lettuce.webp",
  "tablecast-hanul-wraps-mixed": "hanul-option-wraps-mixed.webp",
  "tablecast-hanul-wraps-extra": "hanul-option-wraps-extra.webp",
  "tablecast-hanul-ssamjang-side": "hanul-option-ssamjang-side.webp",
  "tablecast-hanul-chicken-sauce-yangnyeom": "hanul-option-chicken-sauce-yangnyeom.webp",
  "tablecast-hanul-chicken-sauce-soy-garlic": "hanul-option-chicken-sauce-soy-garlic.webp",
  "tablecast-hanul-chicken-sauce-honey-mustard": "hanul-option-chicken-sauce-honey-mustard.webp",
  "tablecast-hanul-dip-soy-vinegar": "hanul-option-dip-soy-vinegar.webp",
  "tablecast-hanul-dip-chilli": "hanul-option-dip-chilli.webp",
  "tablecast-hanul-bibimbap-protein-beef": "hanul-option-bibimbap-protein-beef.webp",
  "tablecast-hanul-bibimbap-protein-tofu": "hanul-option-bibimbap-protein-tofu.webp",
  "tablecast-hanul-egg-yes": "hanul-option-egg-yes.webp",
  "tablecast-hanul-hotpot-extras-cheese": "hanul-option-hotpot-extras-cheese.webp",
  "tablecast-hanul-hotpot-extras-rice-cakes": "hanul-option-hotpot-extras-rice-cakes.webp",
  "tablecast-hanul-hotpot-extras-ramyeon": "hanul-option-hotpot-extras-ramyeon.webp",
  "tablecast-hanul-glasses-two": "hanul-option-glasses-two.webp",
  "tablecast-hanul-glasses-three": "hanul-option-glasses-three.webp",
  "tablecast-hanul-glasses-four": "hanul-option-glasses-four.webp",
  "tablecast-hanul-ice-standard": "hanul-option-ice-standard.webp",
  "tablecast-hanul-ice-less": "hanul-option-ice-less.webp",
};

export function demoOptionImageKey(optionId: string) {
  const file = optionImageFiles[optionId];
  return file ? demoImageKey(file) : null;
}
